server:
  port: 8080

spring:
  application:
    name: bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://azurecnsum1.b2clogin.com/5497f70a-565c-40b7-92c7-b62049f8638f/v2.0/
          jwk-set-uri: https://azurecnsum1.b2clogin.com/5497f70a-565c-40b7-92c7-b62049f8638f/discovery/v2.0/keys?p=B2C_1_signupsignin
      client: {} # placeholder si se requiere más adelante
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: productos
          # uri: http://host.docker.internal:8081
          uri: http://productos:8081
          predicates:
            - Path=/api/productos/**, /api/estados-diseno/**, /api/estados-orden/**, /api/cloudinary/**, /api/productos-personalizados, /api/productos-personalizados/**, /api/ordenes, /api/ordenes/**, /api/carrito/**, /api/carritos/**, /api/categorias/**, /api/colores/**, /api/thumbnails/**, /api/tallas/**, /api/fuentes/**, /api/disenos/**
        - id: usuarios
          filters:
            - TokenRelay
          # uri: http://host.docker.internal:8082
          uri: http://usuarios:8082
          predicates:
            - Path=/api/usuarios/**, /api/auth/**

  mvc:
    cors:
      mappings:
        "/actuator/**":
          allowed-origin-patterns: "*"
          allowed-methods: "GET"
          allowed-headers: "*"
          allow-credentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    com.rabbithole.bff.config: DEBUG # muestra los logs del converter
